spring:
  application:
    name: book-dlq-service
  data:
    mongodb:
      uri: mongodb://admin:123@localhost:27017/book_dlq_db?authSource=admin
      auto-index-creation: true

server:
  port: 8082
